const kernel = {
  tagline: "The Five Needs Engine",
  intro: [
    "The kernel is the part of your Human OS that sets priorities. The Five Needs — Safety, Connection, Competence, Autonomy, Meaning — are your built-in drivers. When they're met, you feel steadier and behave with more flexibility. When they're threatened, you get emotional signals and protective behavior.",
    "Here's the practical rule: emotion to need gap to next choice. Name the emotion, identify which need is threatened or starving, then pick a first move you can do in under 10 minutes. You're not trying to “feel better.” You're trying to meet the need cleanly enough that your system stops sounding the alarm.",
    "One important constraint: if you're in Survival or Shutdown (Chapter 3), run a state tool first. State distorts needs perception — especially Safety and Connection. Don't negotiate your life while your firmware is screaming.",
  ],
  controls: [
    "The kernel determines what your system prioritizes and how it interprets emotions. It strongly influences motivation, mood, resilience, conflict behavior, attention, procrastination, self-worth, boundary strength, meaning, and habit stability.",
    "When the kernel is unstable, you don't lack discipline — you lack clarity. You start thrashing, trying random fixes for symptoms that are being generated by unmet needs.",
  ],
  howItFails: {
    intro: "Kernel failures show up as chronic misalignment — you're trying to meet real needs with strategies that create new problems.",
    patterns: [
      { name: "Threat-first living (Safety)", body: "You interpret neutral signals as danger or criticism. You obsess over control and certainty, avoid risk or feedback, and feel tense even when life is objectively okay." },
      { name: "Connection friction", body: "You feel unseen, unsupported, or underappreciated. You keep score and build resentment, withdraw or test people, and read neutral tone as rejection." },
      { name: "Competence collapse / perfectionism", body: "Tasks feel heavier than they should. You procrastinate or freeze at the start line, avoid feedback, fear looking foolish, and overwork to “prove” yourself." },
      { name: "Autonomy rebellion / resentment", body: "You feel trapped by obligations. You comply outwardly and resist inwardly — disengaging, “forgetting,” or getting angry about lack of choice." },
      { name: "Meaning drift / cynicism", body: "You feel bored, numb, or empty. You stay busy but feel pointless, chase distraction or novelty, and find yourself wondering whether any of it matters." },
    ],
  },
  whyItFails: {
    heading: "Needs compete, so trade-offs are unavoidable",
    paragraphs: [
      "You can't maximize all five needs at once. Safety wants predictability. Autonomy wants freedom. Connection wants compromise. Competence wants focus. Meaning wants long-term alignment. Problems happen when one need dominates chronically — Safety under stress is the most common — or when you meet one need by crushing another, like buying autonomy through rebellion that destroys connection.",
      "When Safety feels threatened, your system prioritizes protection over progress. That's normal. It's also why “just be more confident” isn't advice — it's noise. In Survival state, Safety and Autonomy hijack behavior: protect, control, escape, argue, withdraw. In Shutdown, Meaning and Competence go offline: numb out, delay, “why bother?”",
      "Your system will also choose whatever closes the need gap fastest — especially when tired or stressed. That's why smart people repeatedly do things they regret: scrolling instead of sleeping, avoidance instead of progress, control instead of trust. The goal isn't to stop needing relief. The goal is to upgrade your relief strategies so they don't wreck your life.",
      "Behavior is an attempt to close a need gap. The loop: a need activates, you feel a gap (emotion, tension, urge), you make a choice to close it, you get a payoff (relief, control, attention, escape, progress), and your system learns “do that again.”",
      "Your Quality World is the set of internal pictures you're trying to create or protect — what success should look like, what respect means, what a good relationship feels like. Most conflict isn't bad people. It's mismatched pictures. A useful question: “What picture am I protecting right now — and is it realistic, shared, and worth the cost?”",
      "Total behavior includes doing, thinking, feeling, and body. You can most directly steer doing and thinking. Feelings and body often follow — especially when you're inside usable range. You don't have to wait for motivation to arrive. You can steer your system with a small next behavior.",
    ],
  },
  maintenancePlan: {
    heading: "Pick one or two tools. Not five.",
    tools: [
      { name: "Emotion → Need translation", body: "Name the emotion in one word. Ask which need is threatened or starving. Write “I'm feeling ___ because I need ___.” Then choose a first move under 10 minutes that supports that need." },
      { name: "Need Negotiation", body: "Identify the need and your current strategy, then ask: “Does this strategy meet the need long-term, or only relieve discomfort short-term?” List three alternatives with lower cost, and do the smallest one today." },
      { name: "Total Behavior lever", body: "Pick one Doing action under 5 minutes and pair it with one Thinking shift — “What's the smallest next true step?” Feelings often follow when the system sees forward motion." },
    ],
    story:
      "Leah keeps procrastinating on a project that matters. She calls it laziness. She runs the Needs Scan: Competence is highest (fear of failing), Autonomy is second (she feels forced), and Meaning is elevated (she cares, which adds pressure). She uses Total Behavior: a 2-minute start and a thinking shift. She defines “good enough” for the first draft. Two days later she has momentum — not because she became a different person, but because she used better levers to meet the need.",
  },
};

export default kernel;
